version: '2'

services:

  orientdb:
    image: orientdb
    environment:
      ORIENTDB_ROOT_PASSWORD: kj3KiwqGHrUWKp8t51MM
    ports:
      - 2424:2424
      - 2480:2480
    volumes:
      - orientdb_datases:/orientdb/databases
      - orientdb_backup:/orientdb/backup

  elk:
    image: sebp/elk
    volumes:
      - elk-data:/var/lib/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
      - 5044:5044

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_NODENAME: cursuri-iso@localhost
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  orientdb_datases:
    external: false
  orientdb_backup:
    external: false
  elk-data:
    external: false